# 这是数据库 MySQL 模式启动的配置
server:
  port: 8848
  tomcat:
    basedir: logs

# 数据库存储存储配置文件
db:
  num: 1
  host: ${MYSQL_HOST:iserver-mysql}
  port: ${MYSQL_PORT:3306}
  database: ${MYSQL_DB:iserver_nacos}
  user: ${MYSQL_USER:root}
  password: ${MYSQL_PWD:root}
  url:
    0: jdbc:mysql://${db.host}:${db.port}/${db.database}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true


nacos:
  # 单实例模式启动
  standalone: true
  core:
    # 授权认证相关：https://nacos.io/zh-cn/docs/auth.html
    # 授权认证相关：https://nacos.io/zh-cn/docs/v2/guide/user/auth.html
    auth:
      # 是否开启认证
      enabled: true
      # 所启用的Nacos的鉴权插件的名称，与`com.alibaba.nacos.plugin.auth.spi.server.AuthPluginService`的`getAuthServiceName`返回值对应
      system.type: nacos
      default.token.secret.key: SecretKey012345678901234567890123456789012345678901234567890123456789
      plugin.nacos.token.secret.key: VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=

  # 官方配置中复制过来的
  security:
    ignore:
      urls: /,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**

spring:
  datasource:
    platform: mysql
  security:
    enabled: true
  boot: # 接入 spring boot admin
    admin:
      client:
        url: http://iserver-monitor:5001
        username: iserver
        password: iserver888888
        instance:
          prefer-ip: true
    application:
      name: nacos-console

useAddressServer: true